### PR TITLE
Updated wetkit_bootstrap to version 4.32

### PR DESCRIPTION
**Pull request by pzsurka**

### CODE REVIEW

**Comment by joejoseph00** [comment]
@pzsurka What about version 4.38 ?
4.32 has some bugs

**Comment by rikarux** [comment]
@joejoseph00 are you talking about wetkit_bootstrap or about wet-boew?

**Comment by joejoseph00** [comment]
talking about wet-boew

**Comment by joejoseph00** [comment]
ok sorry ya ignore my message, this is about wetkit_bootstrap lol
Thanks!

**Pull request closed without merging**
