### PR TITLE
Variety of Fixes: Status Messages, Mega Menu, Default Content, Move CSS to hook_libraries_info

### PR DESCRIPTION
**Pull request by sylus**
Variety of Fixes: Status Messages, Mega Menu, Default Content, Move CSS to hook_libraries_info
#268

### CODE REVIEW

**Comment by sylus** [comment]
Bunch of Fixes

1) Some Message Styles implemented in Drupal Status Messages from: http://wet-boew.github.com/wet-boew/demos/grids/grid-base-eng.html




2) Markup has been validated Front + Node page.



3) Markup + Integration with WET is a bit tighter using Libraries API v2.x and jQuery Mobile now works great on lowest media query with Drupal.



and



5) Intranet Theme is working again

**Comment by sylus** [comment]
@pjackson28, @mgifford, @openplus, @joel-osc, @StephenOTT, @sinkinsona

**Comment by sylus** [comment]
Update website: http://wet.openplus.ca/

**Comment by StephenOTT** [comment]
Make sure to run a fresh install.  Update breaks theme

**Comment by StephenOTT** [comment]
@sylus Large bug with panels again.  
If you enter "customize this page", select save, go back into customize this page, and then select save again, the entire page is wipped out.

**Comment by sylus** [comment]
Yeah that is part of the same bug just manifested differently see: https://github.com/wet-boew/wet-boew-drupal/issues/184#issuecomment-8001488

**Pull request merged**
