### PR TITLE
MISC: Abbreviate and unobfuscate drush make files

### PR DESCRIPTION
**Pull request by patcon**
Couple things I noticed while looking through the makefiles:
- No need to specify the project type (module/theme/etc) when downloading from drupal.org
- Drush 5.6 allows you to set defaults, which can be used for specifying the `contrib` subdir
- No need to specify drupal core project outside `drupal-org-core.make` (just more stuff to bump later)
- Why not just follow drupal distro conventions with `drupal-org-core.make` and `drupal-org.make`, and remove `wetkit.make` and `wetkit-core.make`
- Use local references for patchs and files (like `includes[]` items) whenever possible. This will help ensure reproducible builds in the future, which will likely become more important as your build process changes. For example, if I want to try to rebuild a commit from last week, I don't want to build to include files from the HEAD of master branch:
  
  https://github.com/wet-boew/wet-boew-drupal/blob/master/build-wetkit.make#L4
  
  (There are obviously some other places that would need to be changed to facilitate truly reproducible builds, but that is perhaps a larger discussion :)

Will add a PR in a few minutes. Feel free to annotate with any concerns, and maybe I can explain them better

### CODE REVIEW

**Comment by sylus** [comment]
Hey @patcon your feedback makes a lot of sense!

I didn't realize about the project types :) Definitely good advice!

As for the wekit make files as they seem redundant for sure they can be removed, it was only added so people weren't confused since drupal.org has nothing to do with the build but would be needed for a future mirror on d.o. However should follow the DRY principle where possible so I tend to agree with your point.

I like the idea of using drush 5.6 to specify defaults but assuming that will break alot of builds for everyone currently using an older version?

Also may  have to hold up on using drush 5.6 features as drush.ws still does not include an drush installer for windows :( So alot of government workers won't be able to install. Hopefully it will get released soon as includes proper translation support :)

The local references definitely make sense :)

**Comment by patcon** [comment]
Ah... that makes a ton o sense :)
Acquia also doesn't have it installed yet. For reference: https://twitter.com/patconnolly/status/237028129082851329

Also, in regards to specifying the type every time, it's unnecessary whenever a module is being fetched from d.o as tarballs -- nothing to do with where the profile is hosted :)

Fetching git from d.o still needs it. And I like how you guys still include the branch and version entries with commit hash even when not explicitly necessary -- help makes it more self-documenting, which is awesome

So would the PR be acceptable if I add the `contrib` subdirs back in?

**Comment by sylus** [comment]
For sure! 

I think there are one or two places where we are missing the commit hash but definitely making an attempt :)

Anyways I will gladly accept the next commit. 

It is weird the travis ci server is not kicking in though :S It must only be tied to my account for pull requests.

**Comment by sylus** [comment]
Also you guys at myplanetdigital are pretty amazing :) Great to have you helping!

**Comment by patcon** [comment]
Maybe because I'm not a member of the org?

Oh hey, one more thing. What are your thoughts on using the offiicial d.o tarball as much as possible? I see that you guys are using the commit hashes and git repos fairly often, and I'm guessing it's because the patches in queue usually apply only to commits in limbo? In the interest of stability, we usually try to only apply patches that solve the problem we're tackling -- using a dev release plus a patch usually includes lots of other junk, which has not yet been vetted by the community as it's still essentially dev-release code.

What if I documented how to reroll patches in the queues against a stable version of the module, and we could just repost that patch in the queues (for others), and apply it the project? As in, would it make sense to have a development policy of only applying patches the the problems we're solving, applicable only to actual d.o releases?

**Comment by patcon** [comment]
haha thanks man. Honestly, when I came across this project a couple weeks ago, I was totally blown away by how a government team was being given such amazing latitude to do cool things! No foolin. :)

**Comment by patcon** [comment]
Is there a public IRC channel for this project, by the way?

**Comment by sylus** [comment]
Hey @patcon unfortunately for alot of the build we are syncing with the rapid dev of panopoly which is pretty much on a daily basis so would require a bit of effort to reload? 

I have talked with populist about this and he is thinking about reaching beta5 in a few weeks. Once we hit that point can probably branch off and have a more stable patching system in place. We are having an official release for September 17th and would have follow the d.o tarball incredibly closely by then.

As for an irc channel we currently don't but since we are getting more and more contributors now would probably be a great idea!

**Comment by patcon** [comment]
Ok, makes sense. Have you heard of this patch:
[Make install profiles inheritable](http://drupal.org/node/1356276)

The idea is that instead of chasing another install profile, you can have your profile with one or more "base" install profiles, and those are downloaded via `build-wetkit.make` and its modules/themes/libs are loaded appropriately. Haven't had time to dig through all the ways you're using panopoly, so maybe it doesn't make sense, but thought I'd toss it out there!

Also, seems the windows installer is pretty simple to update -- just update the submodule and edit a few files:
https://github.com/patcon/Drush-on-Windows-Installer#readme

Opened an issue to find out how we can get an official release pushed out.

**Comment by sylus** [comment]
Thanks @patcon and yeah me and populist discussed the inheritable profiles unfortunately we deviate in a few areas that at least currently look like the inheritance wouldn't really work. 

The chief deviation being the multilingual support and the fact that ours versions of panopoly_demo and panopoly _pages are different as we have to support completely different panels layouts and default content. Additionally panopoly_search is using search api and it looks like we will be using apachesolr + apachesolr multingual for ours. As well we are bringing in a version of tinymce that CTA spend alot of money on building so would render panopoly_widgets as very different. https://github.com/wet-boew/wet-boew-drupal/issues/193 (I was hoping could have went Aloha but oh well)

Panopoly Magic and Panopoly Admin are closely the same except for a few strongarm variables though.

Down the line it would be ideal to use this methodology perhaps with features overrides and inheritable profiles. If only so I don't have to keep syncing lol! :)

**Comment by sylus** [comment]
Yay Travis Bot! and thank you @patcon!

**Comment by patcon** [comment]
Haha I also love non-evil robots

And no hey, totally fair. You guys seem to have a pretty slick workflow going on, so whatever works! Night dude

**Comment by sylus** [comment]
Even better workflow now that you cleaned it up a bit! :) And night!

**Comment by sylus** [comment]
Hey @patcon I had to modify the build-wetkit.make again as just including the relative path "include = drupal-org-core.make" broke part of the workflow. (See #233)

For instance:

```
drush make --prepare-install --no-gitinfofile --working-copy https://raw.github.com/wet-boew/wet-boew-drupal/master/build-wetkit.make drupal_wet
```

Would no longer work since the include would be relative to nothing. You would have to download the whole repo or git clone first.

What do you think?

**Comment by patcon** [comment]
Rats. I had a reply all typed out yesterday, but I think I changed browsers before submitting. I went into a whole big explanation on why cloning the whole repo is likely a little more future-proof, but alas...

The gist of it was simply that, as the build process becomes more mature, it's likely going to become more than a single 'drush make' line. It will probably make most sense for it to be a script at some point. And to have a truly reproducible build, we'll need to build the site with the version of the script corresponding to the version of the site we want to build. This won't always be the script from HEAD of master, and so it might make more sense to just jump the gun and starting requiring a clone first :) I believe this will also come into play for local patches stored in the profile, but I might be wrong on that...

Did I do a good enough job explaining that? My suggestion would be to add a clone to the setup instructions, and make that drush make line local, if that makes sense for you guys!

**Pull request merged**
