### PR TITLE
pd

### PR DESCRIPTION
**Pull request by joejoseph00**
Pull request for community review.

### CODE REVIEW

**Comment by StephenOTT** [comment]
I would think WET-BOEW-DP-PD would be a good naming convention

**Comment by StephenOTT** [comment]
@joejoseph00 this works towards the work TBS is doing related to the interoperability work.

@pjackson28 @laurawesley @nschonni

**Comment by nschonni** [comment]
I'm guessing this is the same as "Proactive disclosure"? Looking on the TBS site, they use `pd-dp` http://www.tbs-sct.gc.ca/pd-dp/index-eng.asp
In the Web Usibility standards it looks like "Terms and Conditions" is the preferred verbiage http://www.tbs-sct.gc.ca/ws-nw/wu-fe/sn-ea/terms-avis-eng.asp so maybe `terms-avis`

*\* I'm not part of the Web Standards group or TBS, just my 2 cents

**Comment by laurawesley** [comment]
Is this something we could review at the <a href="https://github.com/wet-boew/wet-boew/wiki/Wet-codefest-2.0-summer-2013">CodeFest</a> to figure out how / what needs to change to be re-purposed for GC and for others?

**Comment by joejoseph00** [comment]
@sylus CANCEL PULL REQUEST

**Pull request closed without merging**
