### PR TITLE
Updates for 4.x branch.

### PR DESCRIPTION
**Pull request by sylus**

### CODE REVIEW

**Comment by joejoseph00** [comment]
I see the problem, it's likely with this commit: 
http://cgit.drupalcode.org/wetkit_language/commit/?h=7.x-4.x

and this commit:

http://cgit.drupalcode.org/wetkit_language/commit/?h=7.x-1.x

The patch found here https://www.drupal.org/node/1989084 (found in the above commits): was already committed/fixed in the ET 1.x branch 6 months ago.   Please recheck all the above patches to wetkit_language for ET, all the previous patches we were using in alpha are no longer needed in beta according to my checks.  My patch looks a lot different.

see my original patch here:
https://www.drupal.org/files/issues/wetkit_language4x_et_upgrade-2537760-2.patch
and 1x 
https://www.drupal.org/files/issues/wetkit_language1x_et_upgrade-2537760-2.patch

could have been a copy paste issue or something on your behalf, not sure .  Please double check

**Comment by sylus** [comment]
The patches all applied and while committed we are using stable release which didn't have those patches yet. I had to add some very important ones that were committed after beta4. If you check the build is succeeding on applying the new patches and went right to drupal installation.

Behat fails occasionally with the "administrator" role and that is the only error present in the build. This administrator role issue is intermittent and solved in later versions of behat extension.

U can see the patches successfully being applied at: https://travis-ci.org/wet-boew/wet-boew-drupal/jobs/73305552#L497

**Comment by joejoseph00** [comment]
ah ok, behat extension issue, ok.

I'll take your word on the other patches, sounds good.  hopefully no regressions on the new ET, will have to test it when I get back from vacation in two weeks.

**Comment by sylus** [comment]
Turns out was chrome all fixed.

**Pull request merged**
