### PR TITLE
Changed WET license references to target new HTML versions and changed wet-boew.github.com to wet-boew.github.io

### PR DESCRIPTION
**Pull request by pjackson28**
Same change has been made to all other active WET repos.

### CODE REVIEW

**Comment by mgifford** [comment]
Thanks for the update Paul. I'm thinking that @sylus the only one managing pull requests at the moment though.

Let me know if I'm wrong about that.  I think I've got permission technically, but....

**Comment by pjackson28** [comment]
@mgifford The following people have push access to wet-boew-drupal (left off @ symbol so as not to ping them):
- jmdeleon
- joel-osc
- mgifford
- openplus
- sinkinsona
- StephenOTT
- sylus
- thriuin 
- wet-boew/release-management

I could technically merge it in myself since I have push access as well but I not sure what arrangement there is regarding who reviews and merges in pull request.

**Comment by sylus** [comment]
Hey we have switched out to hosting our individual modules into wet-boew-wem so we can more readily mirror with Drupal.org. Closing this pull request but will fix layouts + migration to reflect newer links!

Thanks!

**Comment by mgifford** [comment]
Do you have a link for wet-boew-wem?

What's the roadmap to break down wet-boew-drupal into the individual modules?

**Pull request closed without merging**
