### PR TITLE
Remove TinyCME in favour of CKEditor for v3.1

### PR DESCRIPTION
**Pull request by sylus**

### CODE REVIEW

**Comment by sylus** [comment]
I agree a roadmap is important, but we are pretty feature complete now. Is a roadmap still as pressing given might be switching to maintenance for the time being? I wasn't present yesterday so hoping the minutes will be uploaded soon :)

**Comment by sylus** [comment]
Also just clarifying the tinymce code won't be removed just wont be in as default since CKEditor is superior and officially endorsed by Drupal and WET.

**Comment by sylus** [comment]
There is a lot that needs to be clarified above. Just so you know we have our equivalent to secure sync which is wetkit deployment. This is deployed at Stats Can and is working great. We don't export content + config. And only rely on officially supported Drupal modules. UUID + Services + Queue API + Deploy.

Content is deployed with WetKit Deployment
Config is deployed with Configuration Management

I'll try to find the time to do a more thorough reply soon.

**Comment by sylus** [comment]
Exactly the goal of WET is to not deviate where possible and use only officially support modules. This eases complexity dramatically :) Definitely proud of the not invented here mantra.

**Comment by sylus** [comment]
I have seen Secure Sync. Reasons for using WetKit Deployment are it uses only officially support Drupal modules. Robert literally wrote his own services module + entity dependency module. How are you going to find community support which should be number 1 indicator?

Points:

1) Robert wrote his own entity dependency module
2) Robert wrote his own services module
3) My interface is vastly simpler and easier to use and deploys only entities, even had a UI expert help improve the workflow (confirmed by UofO)
4) Follows the standard convention of Content + Config should be separate.
5) I only extend officially supported Drupal modules (entity dependency + services + deploy)
6) Is actually used in production now

How is it Robert isn't reinventing but I am when I am only extending drupal contrib modules and Robert wrote his own? Also I am pretty sure released WetKit Deployment first.

**Comment by sylus** [comment]
Also the distro is rather lightweight, where are you getting this is big? We are actually on par in size with the UofO distro. Is there any module you see we don't need? The only two I know about are media_youtube + media_vimeo which have been removed in RC2.

According to Travis the distro now installs in 7 mins.

Also keep in mind we are under continuous integration with travis and have all the code fully checked with code sniffer following strict formatting guidelines. Even most Drupal Contrib modules don't go this insane! :)

Anyways should go for a drink because I think there is some confusion and false information your getting.

**Comment by sylus** [comment]
Would it be beneficial for me to give the reasons you at CTA should also move to CKEditor. It does alot of things better then TinyMCE. In fact some of its built in plugins already does what the custom plugin for TinyMCE does!

In addition has some neat options like automatically encoding emails  to prevent bots etc...

**Comment by sylus** [comment]
Benefits of CKEditor
- Officially supported by Drupal and installed by default in Drupal 8
- WET-BOEW is going to only support CKEditor as the defacto standard
- Immensely better documentation @ http://docs.ckeditor.com/
- CKEditor is now on GitHub and should soon overtake TinyMCE
- Better Accessibility work
- Inline Editing Support in Drupal
- Better French integration
- More plugins
- Better Architecture.
- 35% Faster across the board

**Comment by sylus** [comment]
Honestly I'd just convert the TinyMCE plugin to CKEditor which shouldn't be too hard. I'll take a look at doing that. Some of the features you mentioned above are already in CKEditor.

**Comment by strinh** [comment]
I'm having a bucket of popcorn and enjoying the love / hate we're getting here on secure syndication, however I think things are starting to get off track.  Heated debates about deploying content, who knew?! 

When Will and uOttawa met about Deploy vs. Secure Syndication, we agreed that although it started pretty far apart, we're actually doing some very similar things (we are both using UUID and both using Services) and we foresee a future (this summer even perhaps) where we try to bring the two solutions together in such a way that we all use a common base that uses the fantastic interface that Will built but at the same time is modular enough to do some of the things uOttawa needs / wants to do.  

I think that as a community we can make this happen, even when our basic philosophies differs when it comes to content vs. configuration (and we agree, we definitely differ from the general Drupal population but we don't think that's necessarily a bad thing ;).  

Part of the problem we (uOttawa) see here is that there simply isn't enough communication going on to see the full direction of WET.  We all agreed on the call yesterday.  The reality is that with this many people adopting WET (good thing), it makes us a little less agile when it comes to decisions and without that communication, it makes it difficult to work collaboratively.

All that said, when it comes to Secure Syndication, we need to advance on it (Deploy didn't work for us when we looked it and Will hadn't spent the time yet to make it happen), but we fully plan on trying to create a common tool for deploying any data (regardless if it is content, configuration or otherwise) through a single, simple to use interface (Will's interface is pretty fawesome!).

**Comment by strinh** [comment]
Oh... and that drink comment from Will.  Anyone one for a few wobbly pops at 1848?

**Pull request merged**
