### PR TITLE
New selenium test

### PR DESCRIPTION
**Pull request by mtndan**
Hi, at Drupal4Gov we created a simple Selenium test to validate that search works. Can you please accept?

### CODE REVIEW

**Comment by sylus** [comment]
Hey thanks so much for this pull request!

It looks great but something is up with the CI environment when trying to load images from /sites/default/files/

https://travis-ci.org/wet-boew/wet-boew-drupal/builds/4965669

I think something to do with permissions on that folder so is likely something I need to fix in travis_install.sh perhaps chmod -R 777 /sites/default/files once that is fixed I will merge this pull request!

**Comment by mtndan** [comment]
Ok cool! It was a fun learning experience. One of our crew is working on a
selenium test for the browser based install too.

On Thu, Feb 21, 2013 at 4:20 PM, William H notifications@github.com wrote:

> Hey thanks so much for this pull request!
> 
> It looks great but something is up with the CI environment when trying to
> load images from /sites/default/files/
> 
> https://travis-ci.org/wet-boew/wet-boew-drupal/builds/4965669
> 
> I think something to do with permissions on that folder so is likely
> something I need to fix in travis_install.sh perhaps chmod -R 777
> /sites/default/files once that is fixed I will merge this pull request!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wet-boew/wet-boew-drupal/pull/755#issuecomment-13913497.

## 

Dan Katz

http://www.linkedin.com/in/mtndan

**Comment by StephenOTT** [comment]
:+1:

**Comment by StephenOTT** [comment]
@mtndan - idea for you: Would be amazing if we had a selenium test for testing Browser based install process. ;)

**Comment by mtndan** [comment]
Working on it!

On Friday, February 22, 2013, Stephen Russett wrote:

> @mtndan https://github.com/mtndan - idea for you: Would be amazing if
> we had a selenium test for testing Browser based install process. ;)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wet-boew/wet-boew-drupal/pull/755#issuecomment-13963283.

## 

Dan Katz

http://www.linkedin.com/in/mtndan

**Comment by StephenOTT** [comment]
@mtndan - any luck with the browser install process test?

**Comment by mtndan** [comment]
Hi Stephen, I haven't put any time on it yet. Hopefully this week.

On Fri, Mar 1, 2013 at 3:18 PM, Stephen Russett notifications@github.comwrote:

> @mtndan https://github.com/mtndan - any luck with the browser install
> process test?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wet-boew/wet-boew-drupal/pull/755#issuecomment-14309180
> .

## 

Dan Katz

http://www.linkedin.com/in/mtndan

**Pull request closed without merging**
