### PR TITLE
Updates to the wetcleanup for tinymce

### PR DESCRIPTION
**Pull request by yogaboy**
Use grid row/column as part of heading id, interpret colspan as section
heading, replacing when another colspan heading is found (useful for
balance sheet type tables), omit headers attribute from heading cells to
avoid repetition of heading titles

### CODE REVIEW

**Comment by sylus** [comment]
@joejoseph00 can you confirm these fixes are acceptable? Then will bring this in right away.

**Comment by joejoseph00** [comment]
@sylus, ok, I'll investigate and test in my env asap.

**Comment by joejoseph00** [comment]
I'm currently testing this functionality right now.  I will provide feedback shortly.  Have already made changes to the fr.js  and created a new pull request for those files.

**Comment by joejoseph00** [comment]
Hi @yogaboy , appologies 21 day delay, I am trying to test the "Addition of column splitter for parallel lang text" , but I was unable to get this function to work the way I was expecting.  I pasted a three column table into the tinymce editor, selected the "extract column content" but nothing seemed to happen.  I'm not sure where to begin debugging as I'm not sure what the expected behaviour is.  I was hoping this was going to be similar to the E|F splitter or at least copy one of the columns into the clipboard .  Does this new functionality depend on the University of Ottawa bilingual side-by-side interface?  

For the first commit (described in the paragraph below), I'll have to assume it works, nothing crashed, but I'm not sure how to test them.

"Use grid row/column as part of heading id, interpret colspan as section
heading, replacing when another colspan heading is found (useful for
balance sheet type tables), omit headers attribute from heading cells to
avoid repetition of heading titles"

Going back to the "Addition of column splitter for parallel lang text" plugin add in for the TinyMCE WETKIT tools:

While the function labels show up in the WAS (Wetkit tools) menu, nothing seems to happen when it's clicked.  In the old D6 E|F_splitter a modal dialog as illustrated in the attached photo:

To test the new code I pasted in a sample table that works in the old D6 tiny MCE but nothing happens.

See illustration below:
EF_split_D6_beforeSplit
EF_split_D6

@yogaboy , please assist.  Thanks

**Comment by joejoseph00** [comment]
HI @sylus, icing this test until April 26.
Because I just got an autoresponse from Yogaboy, he won't be able to respond until April 26
"I am away from April 10th to April 26th inclusive. I will not be able to check in with email regularly, if at all."

**Comment by joejoseph00** [comment]
@yogaboy , now that you're back from holidays, can I give you a quick phone call about this on monday some time?

**Comment by joejoseph00** [comment]
@yogaboy , 
The E|F splitter plugin must be able to predict where the second TinyMCE will be located as well as the first.  Content will be split and put in the right place provided that the code can predict where it's going to be.  This makes assumptions about current behaviour of the dual_language_editor module.

Current behaviour of the entity translation based latest and greatest version of the "dual_language_editor"

the pattern for the side by side interface.  TinyMCE is inside an iFrame:

Index is 0 based.  Content types can have 0 to many fields.  The TEST content type only has one side-by-side field.
(the dual language editor can be set French|English or English|French but the id field of the iFrame stays the same either way)

English first field:
iframe id="edit-body-en-0-value_ifr"
body id="tinymce"

French first field:
iframe id="edit-body-fr-0-value_ifr"
body id="tinymce"

Second english field:
iframe id="edit-body-en-1-value_ifr"
body id="tinymce"

Second french field:
iframe id="edit-body-fr-1-value_ifr"
body id="tinymce"

and so on, 2
English
iframe id="edit-body-en-2-value_ifr"
body id="tinymce"

French
iframe id="edit-body-fr-2-value_ifr"
body id="tinymce"

ans so on, 3
and so on, 4
and so on, 5
and so on, 6
...

**Comment by joejoseph00** [comment]
Follow up on monday

**Comment by joejoseph00** [comment]
so when the onclick functions are renamed to t._extractTableColumn from t._extractTableColum  then it works much better :+1:

**Comment by yogaboy** [comment]
Imagine that ;)
Mike Block Consulting Inc.
57 Fireside Crescent
Ottawa, ON   K1T 1Z3
T: 613-521-0298

-----Original Message-----

**Comment by joejoseph00** [comment]
@yogaboy 
@sylus 
Mike, I'm so excited about the work we've done here (I take a very small part of the we)

There's still some quality assurance to do before we can submit the code.

But here's some screenshots.

First step

Second step, select split F|E  (in our case the French is on the left side, others might chose split E|F)

Here's the result, table is gone on left, column content is split appropriately.

**Comment by joejoseph00** [comment]
@sylus, notice the activated icons on TinyMCE in the above illustrations, how can we set those icons (plugins) activated by default in the wetkit distribution so that others will get these as defaults?  Our expert says that these features are bread and butter.

Bold, Italic, Underline, Strike-through, Align left, Align center, Align right
Justify, Bullet list, Numbered list, Outdent, Indent, Undo, Redo, Unlink, Block format, Styles
Forecolor, Visual aid, Remove format, Character map, 
Fullscreen, 
Paste text, Paste from Word
Table , Media, 
WetKit Cleanup Tools,  Insert Templates, Spell Check, Caption Filter,
Media browser, Teaser break

**Comment by joejoseph00** [comment]
We may want to add more plugins by default, might want to talk with our comms guys first.  I'll have them test it out a bit more.

We're still testing the new feature enhancements for the Wetkit Cleanup tools

**Comment by joejoseph00** [comment]
Not quite ready for merging, but soon.  We'll probably have to create a new merge request, because we have some fixes.

**Comment by sylus** [comment]
Hopefully can get this merged before RC2? Also now that have builds working on Drupal.org would be nice to have it up there soon as well.

I want to release RC2 next week. Doable?

**Comment by joejoseph00** [comment]
Yes doable

**Comment by joejoseph00** [comment]
@yogaboy, we're good for next week's release eh?
I should have some more time tomorrow and friday for quality assurance testing

**Comment by joejoseph00** [comment]
From my testing it works consistently on the latest version of Chrome,
however I've noticed an inconsistency with the latest version of Firefox
Possibly related to garbage collection issues in the javascript engine, but there might be a workaround for that.

**Comment by joejoseph00** [comment]
The latest code is sitting on a test server.  Need a bit of time to do some QA.

**Comment by joejoseph00** [comment]
@sylus We're ahead of schedule, good for RC2
The latest pull request is fully tested and ready to be merged.

Merging this code will give you:
Single editor support for first or last populated Column extraction.
Offers dual language split with single editor support (column extraction). 
Support for EN|FR or FR|EN conversion, either editor usable in dual mode. 
The new split feature shows up in the menu when the UOttawa dual language editor is enabled. 

Tested under:
Chrome Version 26.0.1410.64 (PASS), 
FFv15 (PASS), 
FFv20 (FAIL). Note: FFv20 randomly has issues due to FFv20 issues and not TinyMCE or wekitcleanup.

**Comment by joejoseph00** [comment]
@sylus Merge at Will (pun intended).   Props out to Mike Block Consulting. @yogaboy 

https://github.com/yogaboy/wet-boew-drupal/commit/7657421ed43d2b7a6eb6bc79c8587a82e150161c

**Comment by yogaboy** [comment]
Thanks Joseph!

Glad to have that in J

**Comment by joejoseph00** [comment]
@sylus is this going to make it into RC2?  It's ready to be merged.  As mentioned previously it works with or without the UOttawa stuff.  Any questions?

**Comment by joejoseph00** [comment]
Hi @sylus , just a reminder to please merge https://github.com/yogaboy/wet-boew-drupal/commit/7657421ed43d2b7a6eb6bc79c8587a82e150161c
the code is tested and is ready to go.  If you have any questions, please ask.

**Comment by sylus** [comment]
Hey @joejoseph00 we are branching our modules into individual repos as will facilitate better workflow want push access to wet-boew-wem/wetkit-wysiwyg?

**Comment by joejoseph00** [comment]
Hi @sylus, sounds exciting!  Sure, please give me push access to wet-boew-wem/wetkit-wysiwyg.

**Comment by joejoseph00** [comment]
BTW, I retested on FF21 and it's a PASS, as well as Chrome, Safari

**Comment by sylus** [comment]
K u have push access to the repo. Can I have your drupal account name so you can push to that repo as well?

**Comment by sylus** [comment]
Since we now have individual repo's this will have to be filled to wetkit-wysiwyg.

**Pull request closed without merging**
