### PR TITLE
Update drupal.org.make and changelog.md

### PR DESCRIPTION
**Pull request by sylus**

### CODE REVIEW

**Comment by nschonni** [comment]
I know you've started to use the Release tab, so maybe this is a good time to kill the Changlog.md and just point it there

**Comment by sylus** [comment]
Can't do that sadly as use the change log file over at drupal.org repo and it gets pulled in as well for our Docpad documentation site.

**Comment by nschonni** [comment]
Gotcha :smile: 
Funny that you're using DocPad for your docs :wink:

**Comment by sylus** [comment]
Yeah I actually really like it as a replacement for the wiki functionality in github. Particularly because I can use jade, eco, handlebars and whatever other system I want :) Yay fun!

https://github.com/wet-boew-wem/website

**Pull request merged**
