### PR TITLE
Update page--panels--base.tpl.php

### PR DESCRIPTION
**Pull request by d-shields**
This puts in the default drupal site logo - almost exactly how its done in AdaptiveTheme core

### CODE REVIEW

**Comment by sylus** [comment]
Think this looks good but have to make sure of a few things:

1) I think this was removed initially because WET displays its own logo through CSS. Does the addition of these div's + img break mobile?
2) Can you fix the padding https://github.com/wet-boew/wet-boew-drupal/pull/803/files#L98
3) Please update all other documents.

As long as the mobile isn't broken and this isn't used by default don't see a problem on adding this.

**Comment by d-shields** [comment]
Sorry it took so long to get back to this.
It doesn't seem to break the mobile theme, so I'll get those 4 files fixed up tomorrow.

**Comment by mgifford** [comment]
So was the change incorporated? Not sure what the status is that it's been closed.

**Comment by d-shields** [comment]
It was never added.
I never completed this.

For now, sites built in wet can't leverage drupal's default logo config through the UI.

**Pull request closed without merging**
